// ============================================================
// responsibilityCatalogue — THE 93 RESPONSIBILITIES A POSITION CAN CARRY
//
// PURPOSE:      The platform-authored list a business owner ticks from when they build a POSITION.
//               Ten areas, 93 rows. WE edit it; a tenant never does. A tenant's own data — their
//               positions, their picks, their frequency overrides — lives in `business_positions`
//               and `business_position_responsibilities` (20260831). Catalogue = code; tenant
//               state = database. Exactly the `TILE_REGISTRY` ↔ `business_modules` split.
//
// DEPENDENCIES: none. Pure data. The MARKS a row carries (sensitive / cannot-be-delegated /
//               no-capability-yet) are NOT in this file — they are DERIVED from
//               `permissionManifest.ts` in `responsibilityMarks.ts`, so there is one authority
//               for what a permission means and this file cannot drift from it (STD-011).
// OUTPUTS:      `RESPONSIBILITY_CATALOGUE`, `RESPONSIBILITY_AREAS`, `FREQUENCY_ORDER`.
//
// ── WHY THIS IS TYPESCRIPT AND NOT A MIGRATION SEED ─────────────────────────────────────────
// `tileRegistry.ts:17-27` already ruled the pattern for a platform-authored catalogue, and the
// role floor is the counter-example that proves it: `20260623_role_definitions…:201` seeded the
// shared floor by migration and **that INSERT never landed on the live project — verified at 0
// rows** (`scripts/seed-role-floor.mjs:4-7`), so every role dropdown rendered empty and nothing
// said why. `20260727_align_floor_to_bundles.sql:27-34` then settled it: *"THE BUNDLE IS THE
// SOURCE AND THE FLOOR IS ITS MATERIALISATION"*, generated and cap-checked, never hand-typed.
// This file carries PERMISSION STRINGS, and `tileRegistry.ts:23` names that as the reason the
// registry is code rather than editable rows: *"a wrong financial permission = a moat leak."*
//
// ── GATING IS BY VERTICAL, NOT BY MODULE (David's ruling ①, 2026-08-31) ─────────────────────
// "Uppot a lot" is a fact about what KIND of business this is, not about what they have paid for,
// and **there is no `grow_ladder` module_key to point at** — `MODULE_CATALOG` holds eleven keys
// and the grow ladder is unbuilt. Pointing these rows at a key that does not exist would hide
// them from everyone, or force minting a no-cost one, which the 2026-08-01 ruling rejected.
// Resolution goes through `verticalsForBusinessType()`, the axis that already exists.
// `moduleKey` stays as a separate nullable column for a row that genuinely tracks a paid module.
// **No row uses it today**, and that is asserted rather than assumed.
//
// ── `permissions: []` MEANS "GRANTS NOTHING". IT DOES NOT MEAN "NOT BUILT". ─────────────────
// 🔴 Measured on the 2026-08-29 draft: **20 rows carry an empty array and they mean three
// different things** — 18 the software cannot represent, 1 needs no software at all (PPL-09,
// train a new member of staff), 1 is partly built and reserved to the account holder (PPL-10).
// Rendering all 20 as *"the software cannot represent this yet"* would tell an owner the product
// is more incomplete than it is, and would print a false claim on a document they hand to a
// person. So `capability` is a DECLARED field with four values and no third option, and
// `responsibilityCatalogue.test.ts` asserts the two cannot drift apart.
// (A9 / D-9 — absent is not empty; R-12 — make the illegal state unrepresentable.)
// ============================================================

/** How often the work comes round. Ordered by `FREQUENCY_ORDER` for rendering. */
export type ResponsibilityFrequency =
  | 'continuous' | 'daily' | 'weekly' | 'fortnightly' | 'monthly'
  | 'quarterly' | 'seasonal' | 'annual' | 'as_needed';

/**
 * Where the work is DONE. Same vocabulary the owner-test board uses (`DEVICE:`) and the 2026-08-23
 * tile-capability ruling reuses — one word for one idea across the platform.
 */
export type ResponsibilityDevice = 'phone' | 'desktop' | 'either';

/**
 * 🔴 WHAT THE SOFTWARE CAN DO ABOUT THIS RESPONSIBILITY — DECLARED, NEVER INFERRED.
 *
 * - `covered`      — TRACE can carry this work today.
 * - `partial`      — some of it is built and some is not; `note` says which half.
 * - `none`         — the business does this and TRACE cannot represent it yet. It is STILL TICKED:
 *                    the description says what the JOB is, not what the app covers.
 * - `not_software` — a real-world act that needs no app capability. **NOT a gap**, and printing it
 *                    as one would be a lie about our own coverage.
 */
export type ResponsibilityCapability = 'covered' | 'partial' | 'none' | 'not_software';

export interface Responsibility {
  /** Stable id. It is what a tenant's pick rows store, so it may never be renamed in place. */
  readonly id: string;
  /** Grouping heading on the picker and in the printed description. */
  readonly area: string;
  /** The sentence an owner reads and ticks. Written as work, not as a feature. */
  readonly text: string;
  /** The frequency shown before the owner touches it; a position may override it per row. */
  readonly defaultFrequency: ResponsibilityFrequency;
  readonly device: ResponsibilityDevice;
  /**
   * `null` = core, every business. A value = only businesses whose `business_type` resolves to
   * that vertical (`verticalsForBusinessType`). AC-1: vertical identity is a VALUE on a row.
   */
  readonly vertical: string | null;
  /** A paid module this row genuinely tracks. No row uses it today (asserted by the test). */
  readonly moduleKey: string | null;
  readonly capability: ResponsibilityCapability;
  /**
   * Hand-declared, and ONLY meaningful for a row citing no permission string at all. A row that
   * cites an `owner-only` string derives the same answer from the manifest — see
   * `responsibilityMarks.ts`. Two facts, one output, and the derivation wins where it applies.
   */
  readonly accountHolderOnly: boolean;
  /**
   * The model strings this work actually exercises. Every one must be in `ALL_MODEL_PERMISSIONS`
   * or the test fails. Empty = grants nothing; read `capability` for why.
   */
  readonly permissions: readonly string[];
  /** Free text for the honest caveat. Rendered on the picker, never on the printed description. */
  readonly note: string;
}

/** Rendering order for frequency — most-often first, within an area. */
export const FREQUENCY_ORDER: readonly ResponsibilityFrequency[] = [
  'continuous', 'daily', 'weekly', 'fortnightly', 'monthly',
  'quarterly', 'seasonal', 'annual', 'as_needed',
] as const;

/** Human label for a frequency. The picker and the document read the same words. */
export const FREQUENCY_LABEL: Record<ResponsibilityFrequency, string> = {
  continuous:  'Throughout the day',
  daily:       'Daily',
  weekly:      'Weekly',
  fortnightly: 'Every two weeks',
  monthly:     'Monthly',
  quarterly:   'Quarterly',
  seasonal:    'Each season',
  annual:      'Once a year',
  as_needed:   'As needed',
};

export const RESPONSIBILITY_CATALOGUE: readonly Responsibility[] = [
  { id: 'SEL-01', area: 'Selling & customers',
    text: 'Serve walk-in customers on the lot',
    defaultFrequency: 'continuous', device: 'phone', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['customers:read', 'inventory:read', 'orders:create', 'orders:read', 'service_offerings:read'],
    note: '' },
  { id: 'SEL-02', area: 'Selling & customers',
    text: 'Quote a price from the price list',
    defaultFrequency: 'continuous', device: 'either', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['inventory:read', 'service_offerings:read', 'tax_rate:read'],
    note: '' },
  { id: 'SEL-03', area: 'Selling & customers',
    text: 'Quote a price outside the price list',
    defaultFrequency: 'as_needed', device: 'either', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['margin:read', 'pricing_recipe:read'],
    note: 'Needs margin to know the floor' },
  { id: 'SEL-04', area: 'Selling & customers',
    text: 'Apply a discount within the tiers the owner set',
    defaultFrequency: 'daily', device: 'either', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['order_discount:apply'],
    note: 'Does not include setting the tiers' },
  { id: 'SEL-05', area: 'Selling & customers',
    text: 'Set or change the discount tiers',
    defaultFrequency: 'annual', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['pricing_recipe:update', 'order_discount:apply'],
    note: 'Pricing authority' },
  { id: 'SEL-06', area: 'Selling & customers',
    text: 'Apply a tax exemption to a sale',
    defaultFrequency: 'weekly', device: 'either', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['tax_exempt:apply'],
    note: 'Resale and agricultural certificates' },
  { id: 'SEL-07', area: 'Selling & customers',
    text: 'Create and maintain customer records',
    defaultFrequency: 'daily', device: 'either', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['customers:create', 'customers:read', 'customers:update'],
    note: '' },
  { id: 'SEL-08', area: 'Selling & customers',
    text: 'Merge or correct duplicate customer records',
    defaultFrequency: 'monthly', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['customers:update', 'customers:read'],
    note: '' },
  { id: 'SEL-09', area: 'Selling & customers',
    text: 'Build an estimate or proposal',
    defaultFrequency: 'weekly', device: 'either', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['orders:create', 'orders:update', 'order_items:create', 'inventory:read'],
    note: '' },
  { id: 'SEL-10', area: 'Selling & customers',
    text: 'Follow up an outstanding estimate',
    defaultFrequency: 'weekly', device: 'either', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['orders:read', 'orders:update', 'customers:read'],
    note: '' },
  { id: 'SEL-11', area: 'Selling & customers',
    text: 'Visit a site and scope a job',
    defaultFrequency: 'weekly', device: 'phone', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['customers:read', 'customers:create', 'deliveries.route:read'],
    note: '' },
  { id: 'SEL-12', area: 'Selling & customers',
    text: 'Handle a complaint, warranty claim or replacement',
    defaultFrequency: 'as_needed', device: 'either', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['orders:read', 'orders:update', 'customers:read', 'inventory:read'],
    note: '' },
  { id: 'SEL-13', area: 'Selling & customers',
    text: 'Ask a customer for a review after a job',
    defaultFrequency: 'daily', device: 'phone', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['customers:read', 'deliveries:read'],
    note: '' },
  { id: 'SEL-14', area: 'Selling & customers',
    text: 'Plan and run a marketing campaign',
    defaultFrequency: 'monthly', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['campaigns:read', 'campaigns:update', 'customers:read'],
    note: '' },
  { id: 'SEL-15', area: 'Selling & customers',
    text: 'Decide what the business sells and at what price',
    defaultFrequency: 'annual', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['pricing_recipe:update', 'service_offerings:create', 'service_offerings:update'],
    note: 'Pricing authority' },
  { id: 'MON-01', area: 'Orders & money',
    text: 'Create and price a customer order',
    defaultFrequency: 'continuous', device: 'either', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['orders:create', 'order_items:create', 'order_service_selections:create', 'inventory:read'],
    note: '' },
  { id: 'MON-02', area: 'Orders & money',
    text: 'Issue an invoice',
    defaultFrequency: 'daily', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['orders:update', 'order_items:read'],
    note: '' },
  { id: 'MON-03', area: 'Orders & money',
    text: 'Take a payment',
    defaultFrequency: 'daily', device: 'either', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['orders:update'],
    note: 'Payment handling sits with the accounting system' },
  { id: 'MON-04', area: 'Orders & money',
    text: 'Chase an unpaid balance',
    defaultFrequency: 'weekly', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['orders:read', 'customers:read'],
    note: '' },
  { id: 'MON-05', area: 'Orders & money',
    text: 'Issue a refund or credit',
    defaultFrequency: 'as_needed', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['orders:update', 'order_discount:apply'],
    note: '' },
  { id: 'MON-06', area: 'Orders & money',
    text: 'Reconcile sales against the accounting system',
    defaultFrequency: 'monthly', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['orders:read', 'settings:read'],
    note: '' },
  { id: 'MON-07', area: 'Orders & money',
    text: 'Connect or manage the accounting system',
    defaultFrequency: 'annual', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['settings:update', 'subscription:read'],
    note: 'Must be an admin of the accounting system itself' },
  { id: 'MON-08', area: 'Orders & money',
    text: 'Set or change the sales tax rate',
    defaultFrequency: 'annual', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['tax_rate:read', 'tax_rate:update'],
    note: '' },
  { id: 'MON-09', area: 'Orders & money',
    text: 'Approve and run payroll',
    defaultFrequency: 'fortnightly', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['wages:read', 'wages:update'],
    note: 'Exposes individual pay' },
  { id: 'MON-10', area: 'Orders & money',
    text: 'Pay a contractor or vendor',
    defaultFrequency: 'weekly', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['costs:read', 'costs:create'],
    note: 'Exposes what work costs' },
  { id: 'MON-11', area: 'Orders & money',
    text: 'Review margin and profitability',
    defaultFrequency: 'monthly', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['margin:read', 'costs:read'],
    note: 'Exposes cost and margin' },
  { id: 'MON-12', area: 'Orders & money',
    text: 'Set the annual budget',
    defaultFrequency: 'annual', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['costs:read', 'margin:read'],
    note: 'Pricing and money authority' },
  { id: 'INV-01', area: 'Inventory',
    text: 'Walk the lot and count stock',
    defaultFrequency: 'monthly', device: 'phone', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['inventory:read', 'inventory:create', 'inventory:update'],
    note: '' },
  { id: 'INV-02', area: 'Inventory',
    text: 'Reconcile a count and explain the variance',
    defaultFrequency: 'monthly', device: 'either', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['inventory:update', 'inventory_ledger:read'],
    note: '' },
  { id: 'INV-03', area: 'Inventory',
    text: 'Record a loss - weather, damage, theft or death',
    defaultFrequency: 'as_needed', device: 'phone', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['inventory:update', 'inventory_ledger:read'],
    note: '' },
  { id: 'INV-04', area: 'Inventory',
    text: 'Add a new product to the catalogue',
    defaultFrequency: 'monthly', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['inventory:create', 'inventory:update'],
    note: '' },
  { id: 'INV-05', area: 'Inventory',
    text: 'Set or change a product\'s price',
    defaultFrequency: 'seasonal', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['inventory:update', 'pricing_recipe:update'],
    note: 'Pricing authority' },
  { id: 'INV-06', area: 'Inventory',
    text: 'Import a price list or stock list',
    defaultFrequency: 'annual', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['inventory:import_price', 'inventory:create'],
    note: '' },
  { id: 'INV-07', area: 'Inventory',
    text: 'Retire a product no longer sold',
    defaultFrequency: 'quarterly', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['inventory:update', 'inventory:delete'],
    note: '' },
  { id: 'INV-08', area: 'Inventory',
    text: 'Reserve or commit stock against an order',
    defaultFrequency: 'daily', device: 'either', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['inventory:read', 'orders:read'],
    note: '' },
  { id: 'INV-09', area: 'Inventory',
    text: 'Move stock between locations or blocks',
    defaultFrequency: 'weekly', device: 'phone', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['inventory:update', 'inventory_ledger:read'],
    note: '' },
  { id: 'INV-10', area: 'Inventory',
    text: 'Tell Sales what is short before a customer finds out',
    defaultFrequency: 'weekly', device: 'either', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['inventory:read', 'orders:read'],
    note: '' },
  { id: 'PUR-01', area: 'Purchasing',
    text: 'Order stock from a vendor',
    defaultFrequency: 'monthly', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['costs:create', 'inventory:read'],
    note: '' },
  { id: 'PUR-02', area: 'Purchasing',
    text: 'Receive a delivery and check it against the order',
    defaultFrequency: 'monthly', device: 'phone', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['inventory:create', 'inventory:update', 'costs:read'],
    note: '' },
  { id: 'PUR-03', area: 'Purchasing',
    text: 'Record a vendor invoice',
    defaultFrequency: 'weekly', device: 'either', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['costs:create', 'costs:read'],
    note: 'Exposes what stock costs' },
  { id: 'PUR-04', area: 'Purchasing',
    text: 'Approve a vendor invoice for payment',
    defaultFrequency: 'weekly', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['costs:read', 'costs:update'],
    note: '' },
  { id: 'PUR-05', area: 'Purchasing',
    text: 'Negotiate vendor prices and terms',
    defaultFrequency: 'annual', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['costs:read', 'margin:read'],
    note: '' },
  { id: 'PUR-06', area: 'Purchasing',
    text: 'Maintain the vendor list',
    defaultFrequency: 'quarterly', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['costs:read', 'costs:create'],
    note: '' },
  { id: 'PUR-07', area: 'Purchasing',
    text: 'Allocate freight across a delivery',
    defaultFrequency: 'monthly', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['costs:update', 'costs:read'],
    note: '' },
  { id: 'GRO-01', area: 'Growing',
    text: 'Propagate from seed, cutting or liner',
    defaultFrequency: 'seasonal', device: 'phone', vertical: 'cultivar', moduleKey: null,
    capability: 'none', accountHolderOnly: false,
    permissions: [],
    note: 'No capability yet - the grow ladder' },
  { id: 'GRO-02', area: 'Growing',
    text: 'Decide when a lot is ready to move up a size',
    defaultFrequency: 'seasonal', device: 'phone', vertical: 'cultivar', moduleKey: null,
    capability: 'none', accountHolderOnly: false,
    permissions: [],
    note: 'No capability yet - graduations' },
  { id: 'GRO-03', area: 'Growing',
    text: 'Uppot or graduate a lot and record it',
    defaultFrequency: 'seasonal', device: 'phone', vertical: 'cultivar', moduleKey: null,
    capability: 'none', accountHolderOnly: false,
    permissions: [],
    note: 'No capability yet - the grow ladder' },
  { id: 'GRO-04', area: 'Growing',
    text: 'Set the growing schedule for a season',
    defaultFrequency: 'annual', device: 'desktop', vertical: 'cultivar', moduleKey: null,
    capability: 'none', accountHolderOnly: false,
    permissions: [],
    note: 'No capability yet' },
  { id: 'GRO-05', area: 'Growing',
    text: 'Track how long a variety takes on each rung',
    defaultFrequency: 'continuous', device: 'either', vertical: 'cultivar', moduleKey: null,
    capability: 'none', accountHolderOnly: false,
    permissions: [],
    note: 'No capability yet' },
  { id: 'GRO-06', area: 'Growing',
    text: 'Water and irrigate',
    defaultFrequency: 'daily', device: 'phone', vertical: 'cultivar', moduleKey: null,
    capability: 'none', accountHolderOnly: false,
    permissions: [],
    note: 'No capability yet' },
  { id: 'GRO-07', area: 'Growing',
    text: 'Prune, stake and train stock',
    defaultFrequency: 'weekly', device: 'phone', vertical: 'cultivar', moduleKey: null,
    capability: 'none', accountHolderOnly: false,
    permissions: [],
    note: 'No capability yet' },
  { id: 'GRO-08', area: 'Growing',
    text: 'Maintain the parent-tree and seed-source register',
    defaultFrequency: 'annual', device: 'either', vertical: 'cultivar', moduleKey: null,
    capability: 'none', accountHolderOnly: false,
    permissions: [],
    note: 'No capability yet' },
  { id: 'PHC-01', area: 'Plant health & compliance',
    text: 'Inspect stock for pests and disease',
    defaultFrequency: 'weekly', device: 'phone', vertical: 'cultivar', moduleKey: null,
    capability: 'none', accountHolderOnly: false,
    permissions: [],
    note: 'No capability yet' },
  { id: 'PHC-02', area: 'Plant health & compliance',
    text: 'Plan the preventive treatment programme',
    defaultFrequency: 'seasonal', device: 'desktop', vertical: 'cultivar', moduleKey: null,
    capability: 'none', accountHolderOnly: false,
    permissions: [],
    note: 'No capability yet' },
  { id: 'PHC-03', area: 'Plant health & compliance',
    text: 'Apply a chemical treatment',
    defaultFrequency: 'monthly', device: 'phone', vertical: 'cultivar', moduleKey: null,
    capability: 'none', accountHolderOnly: false,
    permissions: [],
    note: 'No capability yet' },
  { id: 'PHC-04', area: 'Plant health & compliance',
    text: 'Record an application - product, date, target, applicator',
    defaultFrequency: 'monthly', device: 'phone', vertical: 'cultivar', moduleKey: null,
    capability: 'none', accountHolderOnly: false,
    permissions: [],
    note: 'Nothing records a chemical application. order_compliance_records is an order-scoped customer accept/decline receipt (order_id NOT NULL) and does not fit.' },
  { id: 'PHC-05', area: 'Plant health & compliance',
    text: 'Rotate products so pests do not build tolerance',
    defaultFrequency: 'seasonal', device: 'either', vertical: 'cultivar', moduleKey: null,
    capability: 'none', accountHolderOnly: false,
    permissions: [],
    note: 'Needs an application history that does not exist yet.' },
  { id: 'PHC-06', area: 'Plant health & compliance',
    text: 'Hold or arrange the applicator licence',
    defaultFrequency: 'annual', device: 'desktop', vertical: 'cultivar', moduleKey: null,
    capability: 'none', accountHolderOnly: false,
    permissions: [],
    note: 'No capability yet' },
  { id: 'PHC-07', area: 'Plant health & compliance',
    text: 'Manage chemical storage and handling',
    defaultFrequency: 'continuous', device: 'phone', vertical: 'cultivar', moduleKey: null,
    capability: 'none', accountHolderOnly: false,
    permissions: [],
    note: 'No capability yet' },
  { id: 'PHC-08', area: 'Plant health & compliance',
    text: 'Respond to a regulator or an inspection',
    defaultFrequency: 'as_needed', device: 'desktop', vertical: 'cultivar', moduleKey: null,
    capability: 'partial', accountHolderOnly: false,
    permissions: ['audit_log:read'],
    note: 'The audit log is real; the spray record it would produce is not.' },
  { id: 'DEL-01', area: 'Delivery & field',
    text: 'Build the delivery schedule',
    defaultFrequency: 'daily', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['deliveries:create', 'deliveries:read', 'deliveries:update'],
    note: '' },
  { id: 'DEL-02', area: 'Delivery & field',
    text: 'Route the day and sequence the stops',
    defaultFrequency: 'daily', device: 'either', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['deliveries.route:read', 'deliveries:read'],
    note: '' },
  { id: 'DEL-03', area: 'Delivery & field',
    text: 'Assign crews to jobs',
    defaultFrequency: 'daily', device: 'either', vertical: null, moduleKey: null,
    capability: 'partial', accountHolderOnly: false,
    permissions: ['deliveries:update'],
    note: 'Partial - crew assignment is thin' },
  { id: 'DEL-04', area: 'Delivery & field',
    text: 'Load a vehicle against the day sheet',
    defaultFrequency: 'daily', device: 'phone', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['deliveries:read', 'inventory:read'],
    note: '' },
  { id: 'DEL-05', area: 'Delivery & field',
    text: 'Drive a delivery',
    defaultFrequency: 'daily', device: 'phone', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['deliveries:read', 'deliveries.route:read'],
    note: '' },
  { id: 'DEL-06', area: 'Delivery & field',
    text: 'Plant or install on site',
    defaultFrequency: 'daily', device: 'phone', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['deliveries:read', 'deliveries:update'],
    note: '' },
  { id: 'DEL-07', area: 'Delivery & field',
    text: 'Confirm a job complete',
    defaultFrequency: 'daily', device: 'phone', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['deliveries:update', 'orders:update'],
    note: '' },
  { id: 'DEL-08', area: 'Delivery & field',
    text: 'Record what happened on the job and what was needed',
    defaultFrequency: 'daily', device: 'phone', vertical: null, moduleKey: null,
    capability: 'none', accountHolderOnly: false,
    permissions: [],
    note: 'No capability yet - the after-action note' },
  { id: 'DEL-09', area: 'Delivery & field',
    text: 'Set which days take deliveries and which do not',
    defaultFrequency: 'seasonal', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'partial', accountHolderOnly: false,
    permissions: ['settings:update'],
    note: 'Partial - day types' },
  { id: 'DEL-10', area: 'Delivery & field',
    text: 'Price a delivery by distance',
    defaultFrequency: 'daily', device: 'either', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['deliveries.route:read', 'service_offerings:read'],
    note: '' },
  { id: 'EQP-01', area: 'Equipment & site',
    text: 'Maintain the equipment register',
    defaultFrequency: 'quarterly', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'none', accountHolderOnly: false,
    permissions: [],
    note: 'No capability yet - equipment register' },
  { id: 'EQP-02', area: 'Equipment & site',
    text: 'Schedule preventive maintenance',
    defaultFrequency: 'monthly', device: 'either', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['pmi:read', 'pmi:update'],
    note: '' },
  { id: 'EQP-03', area: 'Equipment & site',
    text: 'Perform or arrange maintenance',
    defaultFrequency: 'monthly', device: 'phone', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['pmi:read', 'pmi:update'],
    note: '' },
  { id: 'EQP-04', area: 'Equipment & site',
    text: 'Assign equipment to a crew for the day',
    defaultFrequency: 'daily', device: 'either', vertical: null, moduleKey: null,
    capability: 'partial', accountHolderOnly: false,
    permissions: ['pmi:read'],
    note: 'Partial - no assignment concept' },
  { id: 'EQP-05', area: 'Equipment & site',
    text: 'Report a fault or damage',
    defaultFrequency: 'as_needed', device: 'phone', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['pmi:update'],
    note: '' },
  { id: 'EQP-06', area: 'Equipment & site',
    text: 'Manage the site, buildings and irrigation',
    defaultFrequency: 'weekly', device: 'phone', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['costs:create', 'pmi:read'],
    note: '' },
  { id: 'PPL-01', area: 'People',
    text: 'Invite someone into the system',
    defaultFrequency: 'quarterly', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['team:create', 'team:read'],
    note: '' },
  { id: 'PPL-02', area: 'People',
    text: 'Assign or change someone\'s role',
    defaultFrequency: 'quarterly', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['team:read'],
    note: 'Grants authority to others. The act runs through assign_member_role; team:update is declared-unwired and authorizes nothing, so it is not cited.' },
  { id: 'PPL-03', area: 'People',
    text: 'See who has access and what they can do',
    defaultFrequency: 'monthly', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['team:read'],
    note: '' },
  { id: 'PPL-04', area: 'People',
    text: 'Remove someone\'s access',
    defaultFrequency: 'as_needed', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'partial', accountHolderOnly: false,
    permissions: ['team:read'],
    note: 'Grants authority to others. Removing access is not in the permission funnel yet (R-22 (c)), so the control renders locked with a reason.' },
  { id: 'PPL-05', area: 'People',
    text: 'Set someone\'s pay rate',
    defaultFrequency: 'annual', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['wages:create', 'wages:update'],
    note: 'Exposes individual pay' },
  { id: 'PPL-06', area: 'People',
    text: 'Approve hours or time worked',
    defaultFrequency: 'fortnightly', device: 'either', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['wages:read', 'wages:update'],
    note: 'Exposes individual pay' },
  { id: 'PPL-07', area: 'People',
    text: 'Direct the yard crew day to day',
    defaultFrequency: 'continuous', device: 'phone', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['deliveries:read'],
    note: '' },
  { id: 'PPL-08', area: 'People',
    text: 'Manage contractors and subcontractors',
    defaultFrequency: 'weekly', device: 'either', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['costs:read', 'costs:create'],
    note: '' },
  { id: 'PPL-09', area: 'People',
    text: 'Train new staff',
    defaultFrequency: 'as_needed', device: 'either', vertical: null, moduleKey: null,
    capability: 'not_software', accountHolderOnly: false,
    permissions: [],
    note: 'Needs no software. Not a gap.' },
  { id: 'PPL-10', area: 'People',
    text: 'Promote someone to full authority',
    defaultFrequency: 'as_needed', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'partial', accountHolderOnly: true,
    permissions: [],
    note: 'A role can be assigned today; ownership authority (R-22 Stage 2) is not built.' },
  { id: 'SYS-01', area: 'Oversight & system',
    text: 'Review sales performance',
    defaultFrequency: 'monthly', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['orders:read', 'customers:read'],
    note: '' },
  { id: 'SYS-02', area: 'Oversight & system',
    text: 'Review the schedule and what is coming',
    defaultFrequency: 'weekly', device: 'either', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['deliveries:read', 'pmi:read'],
    note: '' },
  { id: 'SYS-03', area: 'Oversight & system',
    text: 'Review who did what and when',
    defaultFrequency: 'quarterly', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['audit_log:read'],
    note: 'Sensitive - the accountability record' },
  { id: 'SYS-04', area: 'Oversight & system',
    text: 'Configure the business profile and settings',
    defaultFrequency: 'annual', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['settings:read', 'settings:update'],
    note: '' },
  { id: 'SYS-05', area: 'Oversight & system',
    text: 'Turn capabilities on or off',
    defaultFrequency: 'annual', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['subscription:read', 'subscription:update'],
    note: 'Changes what the business is billed' },
  { id: 'SYS-06', area: 'Oversight & system',
    text: 'Manage the subscription and billing',
    defaultFrequency: 'annual', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'covered', accountHolderOnly: false,
    permissions: ['subscription:read', 'subscription:update'],
    note: 'Changes what the business is billed' },
  { id: 'SYS-07', area: 'Oversight & system',
    text: 'Transfer ownership of the account',
    defaultFrequency: 'as_needed', device: 'desktop', vertical: null, moduleKey: null,
    capability: 'none', accountHolderOnly: true,
    permissions: [],
    note: 'Ownership transfer is not built (R-22 Stage 2).' },] as const;

/** Area headings in catalogue order — DERIVED, so adding a row in a new area needs no second edit. */
export const RESPONSIBILITY_AREAS: readonly string[] =
  [...new Set(RESPONSIBILITY_CATALOGUE.map((r) => r.area))];

/** One row by id, or `undefined`. Callers must handle the miss — a stored pick can outlive a row. */
export function responsibilityById(id: string): Responsibility | undefined {
  return RESPONSIBILITY_CATALOGUE.find((r) => r.id === id);
}
