import type { SupabaseClient } from '@supabase/supabase-js';
import type { Invitation } from './types';

// Client-side invitation management. All functions run with the owner's authenticated
// Supabase session. RLS policy inv_owner_all grants the owner full access.

export interface CreateInvitationInput {
  businessId: string;
  name: string;
  email?: string;        // where to send invite email; optional for QR/SMS-only
  phone?: string;        // for SMS delivery
  role: string;
  permissions: string[]; // vertical-defined permission IDs; owner sets before invite is sent
}

export interface CreateInvitationResult {
  invitation: Invitation;
  memberId: string;      // the pre-created inactive business_members row ID
  inviteLink: string;    // ready-to-share URL
}

// Creates an invitation row + an inactive business_members row.
// The token is generated by the database default (encode(gen_random_bytes(32), 'hex')).
// inviteBasePath is the route within the vertical's app (e.g. '/join' or '/accept').
// The full link becomes: {inviteBaseUrl}{inviteBasePath}?token={token}
export async function createInvitation(
  supabase: SupabaseClient,
  input: CreateInvitationInput,
  inviteBaseUrl: string,
  inviteBasePath = '/join'
): Promise<CreateInvitationResult> {
  // 1. Create invitation row (token auto-set by DB default)
  const { data: invitation, error: invErr } = await supabase
    .from('invitations')
    .insert({
      business_id: input.businessId,
      name: input.name,
      email: input.email ?? null,
      phone: input.phone ?? null,
      role: input.role,
    })
    .select()
    .single();

  if (invErr || !invitation) {
    throw new Error(`createInvitation: ${invErr?.message ?? 'no data returned'}`);
  }

  // 2. Pre-create inactive business_members row.
  // Owner sets role + permissions here; they stay locked until the member accepts.
  const { data: member, error: memErr } = await supabase
    .from('business_members')
    .insert({
      business_id: input.businessId,
      name: input.name,
      email: input.email ?? null,
      phone: input.phone ?? null,
      role: input.role,
      permissions: input.permissions,
      active: false,
      invite_id: invitation.id,
    })
    .select('id')
    .single();

  if (memErr || !member) {
    // Roll back the invitation row to avoid orphaned tokens
    await supabase.from('invitations').update({ used: true }).eq('id', invitation.id);
    throw new Error(`createInvitation (member row): ${memErr?.message ?? 'no data returned'}`);
  }

  const inviteLink = `${inviteBaseUrl}${inviteBasePath}?token=${invitation.token}`;

  return {
    invitation: invitation as Invitation,
    memberId: member.id,
    inviteLink,
  };
}

// Revokes a pending invitation by marking it used. The inactive business_members row
// stays so the owner can see who was invited; owner can delete it separately.
export async function revokeInvitation(
  supabase: SupabaseClient,
  invitationId: string
): Promise<void> {
  const { error } = await supabase
    .from('invitations')
    .update({ used: true })
    .eq('id', invitationId);

  if (error) throw new Error(`revokeInvitation: ${error.message}`);
}

// Lists pending (unused, unexpired) invitations for a business.
export async function getPendingInvitations(
  supabase: SupabaseClient,
  businessId: string
): Promise<Invitation[]> {
  const { data, error } = await supabase
    .from('invitations')
    .select('*')
    .eq('business_id', businessId)
    .eq('used', false)
    .gt('expires_at', new Date().toISOString())
    .order('created_at', { ascending: false });

  if (error) throw new Error(`getPendingInvitations: ${error.message}`);
  return (data ?? []) as Invitation[];
}

// Marks expired invitations as used. Run this as a cleanup task.
// Server-side only — requires service key to update rows the owner doesn't own.
export async function expireInvitations(serviceSupabase: SupabaseClient): Promise<number> {
  const { data, error } = await serviceSupabase
    .from('invitations')
    .update({ used: true })
    .eq('used', false)
    .lt('expires_at', new Date().toISOString())
    .select('id');

  if (error) throw new Error(`expireInvitations: ${error.message}`);
  return (data ?? []).length;
}
