-- ════════════════════════════════════════════════════════════════════════════════
-- 20260728b — DEFAULT PRIVILEGES: the durable half of 20260728 (§2, now resolved)
-- ════════════════════════════════════════════════════════════════════════════════
-- APPLY AS: postgres.
--
-- ⚠️ REPO-AUTHORITY RECORD. David applied BOTH statements below by hand and read the catalog
--    back. This file is the replayable form.
--
-- ⚠️ WHY THIS IS A SECOND FILE AND NOT AN EDIT TO `20260728`. That migration's §2 was left
--    deliberately unwritten, pending the `pg_default_acl` read, with the sequencing stated in it:
--    if §1 is applied before the read returns, §2 becomes its own appended file. §1 WAS applied
--    first. Editing an applied migration recreates the exact repo/DB disagreement that record
--    exists to prevent (§6 r1, migrations are append-only). So: `20260728b`.
--
-- ── WHAT `pg_default_acl` SAID, AND WHY §1 ALONE WAS NOT ENOUGH ──────────────────
-- A default ACL on `public` DID grant TRUNCATE and REFERENCES to the client roles. §1 expanded
-- ONCE over the tables existing at apply time; every table created afterwards would have arrived
-- carrying them again. §1 was a point-in-time cleanup; this is the rule that keeps it true.
--
-- The read named `postgres` as the granting role, so `FOR ROLE postgres` is explicit below. This
-- is not decoration — a default ACL is keyed by (grantor, schema, object type), and omitting
-- `FOR ROLE` targets only entries whose grantor is the CURRENT role. Had the entry belonged to
-- another role, the bare form would have run clean, reported success, and changed nothing.
--
-- VERIFIED BY DAVID AFTER APPLY: the `postgres` / objtype `'r'` row in `pg_default_acl` now reads
-- `anon=arwdtm` — **`D` (TRUNCATE) and `x` (REFERENCES) are gone**, INSERT/SELECT/UPDATE/DELETE/
-- TRIGGER/MAINTAIN remain. The letters are the proof; the statement succeeding is not.

BEGIN;

-- Re-assert §1 over today's tables. Idempotent (REVOKE of an unheld privilege is a no-op) and
-- kept here deliberately: on a rebuild the two statements must land TOGETHER, because a default
-- ACL governs only FUTURE objects and never retroactively fixes one already created.
REVOKE TRUNCATE, REFERENCES ON ALL TABLES IN SCHEMA public FROM anon, authenticated;

-- The durable half: every table created BY POSTGRES in `public` from here on.
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE TRUNCATE, REFERENCES ON TABLES FROM anon, authenticated;

COMMIT;


-- ════════════════════════════════════════════════════════════════════════════════
-- 🔴 THE RESIDUAL — NOT FULLY CLOSED, AND THE GAP IS A WORKFLOW, NOT A STATEMENT
-- ════════════════════════════════════════════════════════════════════════════════
-- ✏️ SCOPE CORRECTED 2026-07-28, AFTER THE V4 PROBE (comment-only — no statement in this file was
--    changed, and it had already been applied; recorded inline rather than silently reworded).
--    The first draft said "the dashboard," which was too broad and would have banned a path that
--    is fine.
--
-- THE SAME `ALTER` AGAINST `supabase_admin` WAS **DENIED**. Supabase owns that role and does not
-- grant membership in it, so its default ACL on `public` cannot be altered from here. It is not an
-- oversight and there is no statement that fixes it — it is a property of managed Postgres.
--
-- WHY THAT MATTERS: `supabase_admin` is the role that creates tables WHEN SUPABASE DOES — i.e.
-- **the dashboard TABLE EDITOR**. Its default ACL still grants TRUNCATE and REFERENCES to `anon`.
--
--   ⇒ A TABLE CREATED THROUGH THE DASHBOARD **TABLE EDITOR** ARRIVES WITH `TRUNCATE` AND
--     `REFERENCES` GRANTED TO `anon` ALL OVER AGAIN — silently, looking exactly like every
--     other table.
--
-- ⚠️ THE SQL EDITOR IS **NOT** THE GAP — PROVEN, NOT ASSUMED. The V4 probe below was created
--    through the SQL editor and inherited the **postgres** default: five privileges arrived,
--    TRUNCATE and REFERENCES did not. So the two surfaces people both call "the dashboard" behave
--    DIFFERENTLY, and only one re-grants. Saying "not the dashboard" would have forbidden a safe
--    path and, worse, taught a rule that the next probe visibly contradicts — which is how a
--    correct rule gets discarded wholesale.
--
-- ⚠️ THE WORKFLOW CONSTRAINT THAT FOLLOWS (binding):
--
--        ***  CREATE TABLES THROUGH MIGRATIONS, NOT THE DASHBOARD TABLE EDITOR.  ***
--        ***  (the SQL editor inherits the corrected postgres default and is fine)  ***
--
--    Not a style preference. The migration and SQL-editor paths run as `postgres`, whose default
--    ACL is now correct; the table-editor path runs as `supabase_admin`, whose default ACL cannot
--    be corrected. Same table, same schema, different privileges — decided by which window it was
--    typed into.
--
-- ── AN EXTERNAL CONTROL THAT EXISTS, AND IS NOT OURS ────────────────────────────
-- Supabase's SQL editor warns before running a `CREATE TABLE` without RLS: *"Clients using anon or
-- authenticated keys may be able to access public.<table>."* The platform guards the same shape we
-- spent this week finding. Recorded as an external control that EXISTS — not as something we
-- built, and not as something to rely on: it is a warning on one surface, it is dismissible, and
-- it speaks to RLS rather than to the privilege layer this file is about.
--
-- THE GOOD NEWS: this is DETECTABLE, and the detector is exact. A table in `public` carrying
-- TRUNCATE or REFERENCES for `anon` after this migration was, with near-certainty, created outside
-- the migration path. The privilege is the fingerprint.

-- ════════════════════════════════════════════════════════════════════════════════
-- ✅ VERIFIED 2026-07-28 (David, live at postgres, `bgobkjcopcxusjsetfob`) — ALL FOUR CLEAN.
-- ════════════════════════════════════════════════════════════════════════════════
--  V1 — **ZERO ROWS.** No TRUNCATE and no REFERENCES for `anon` or `authenticated` anywhere in
--       `public`. The negative this migration exists to produce.
--  V2 — ordinary CRUD UNTOUCHED, which is the half that matters more: `anon` on 45 tables,
--       `authenticated` on 46, both at DELETE/INSERT/SELECT/TRIGGER/UPDATE. RLS is still doing
--       exactly the filtering it was always doing.
--       ⚠️ THE 45-vs-46 GAP IS EXPLAINED, NOT A DEFECT: it is
--       `business_inventory_ledger_events` — `anon` was revoked BY HAND yesterday (containment,
--       ledger #159), `authenticated` still holds it. **It resolves when `20260727f` DROPS the
--       view.** Recorded here so a later reader does not re-investigate a known, queued item.
--  V3 — `audit_log` and `business_inventory_ledger` both at **INSERT, SELECT, TRIGGER** per role.
--       REFERENCES gone; TRUNCATE was already gone (`20260624` / `20260720:209`). The tightest
--       privilege set in the schema, and it got tighter — the intended interaction, confirmed.
--  V4 — 🔴 **THE DURABILITY PROOF PASSES.** A fresh table inherited exactly five privileges —
--       DELETE, INSERT, SELECT, TRIGGER, UPDATE — and **NO TRUNCATE, NO REFERENCES.**
--       **That is precisely the distinction the probe exists to make:** the default ACL is LIVE
--       (five privileges arrived, so there WAS something there) **AND** narrowed (two did not
--       arrive). Neither reading alone would have proven it. A statement that had silently
--       no-opped would have produced seven privileges; an absent default would have produced
--       none. Five is the only outcome that means "fixed."
-- ════════════════════════════════════════════════════════════════════════════════

-- ── ASSERTION A — 🔴 THE TABLE-EDITOR-CREATED-TABLE DETECTOR. EXPECT 0 ROWS, ALWAYS, FOREVER.
--    Any row is a table that acquired these privileges outside the migration path — in practice,
--    one created in the dashboard TABLE EDITOR. Remediate with the §1 statement above, then find
--    out who created it and how. ✅ Returned 0 rows on 2026-07-28 (this is V1).
--
-- SELECT c.relname                    AS table_name,
--        a.grantee::regrole::text     AS grantee,
--        a.privilege_type,
--        pg_get_userbyid(c.relowner)  AS owner   -- expect `supabase_admin` on a violation
--   FROM pg_class c
--   JOIN pg_namespace n ON n.oid = c.relnamespace
--   CROSS JOIN LATERAL aclexplode(c.relacl) a
--  WHERE n.nspname = 'public'
--    AND c.relkind IN ('r','p','v','m','f')
--    AND a.grantee::regrole::text IN ('anon', 'authenticated')
--    AND a.privilege_type IN ('TRUNCATE', 'REFERENCES')
--  ORDER BY c.relname, grantee, a.privilege_type;
--
-- ⚠️ READ `pg_class.relacl` VIA `aclexplode`, **NOT** `information_schema.role_table_grants` —
--    AND THIS IS A CORRECTNESS POINT, NOT A PREFERENCE. The information_schema view only exposes
--    grants where the querying role is the grantor or a member of the grantee. Run from a role
--    that is not a member of `anon`, it returns ZERO ROWS ON A DATABASE FULL OF VIOLATIONS —
--    a false green produced by the checker's own permissions. `pg_class.relacl` is the raw catalog
--    and is readable regardless. (`relacl` NULL = owner-defaults-only = no grant to anon at all,
--    so `aclexplode` correctly yields nothing for it.)
--
-- ⚠️ WHERE THIS ASSERTION SHOULD LIVE, AND WHY IT DOES NOT LIVE THERE YET: the schema snapshot
--    checker named in ledger #159b (a committed catalog dump, ~600 rows) **does not exist yet**,
--    and `scripts/verify-universals.mjs` CANNOT host it — that script reads migration .sql files
--    from the repo, and this is a claim about the live catalog, which is precisely the class of
--    fact the repo cannot answer (STD-021 v2.8: privileges are catalog facts). So today this is a
--    query David runs. It is written here in its final form so the checker inherits it verbatim
--    when it is built, rather than being re-derived. Recorded as OWED, not as done.

-- ── ASSERTION B — the default ACL itself. EXPECT `postgres`/`r` to show no `D` and no `x` for
--    anon or authenticated. `supabase_admin`'s row WILL still show them; that is the known,
--    unfixable residual above, not a failure of this migration.
-- SELECT d.defaclrole::regrole AS granting_role, d.defaclobjtype AS obj_type, d.defaclacl AS acl
--   FROM pg_default_acl d
--   JOIN pg_namespace n ON n.oid = d.defaclnamespace
--  WHERE n.nspname = 'public'
--  ORDER BY granting_role, obj_type;

-- ── ASSERTION C — proven by BREAKING it (STD-022). A fresh table is the only thing that
--    distinguishes "the default ACL was fixed" from "there was never one to fix." Rolls back.
--    ✅ RAN 2026-07-28 — five privileges, no TRUNCATE, no REFERENCES. This is V4, and it also
--    established that the SQL editor inherits the POSTGRES default (see the residual above).
-- BEGIN;
--   CREATE TABLE public._privilege_probe (id int);
--   SELECT a.grantee::regrole::text AS grantee, a.privilege_type
--     FROM pg_class c CROSS JOIN LATERAL aclexplode(c.relacl) a
--    WHERE c.oid = 'public._privilege_probe'::regclass
--      AND a.grantee::regrole::text IN ('anon', 'authenticated')
--    ORDER BY grantee, a.privilege_type;
-- ROLLBACK;
--    EXPECT: INSERT/SELECT/UPDATE/DELETE/TRIGGER — and NO TRUNCATE, NO REFERENCES.


-- ── STILL OPEN, RECORDED NOT BLOCKING (carried forward from 20260728, unchanged) ─
-- `anon` HOLDS INSERT / UPDATE / DELETE ON ~45 BASE TABLES, and **RLS is the only line** — it is
-- on everywhere, which is why this is a follow-on and not a hole. Scoping it down needs a corpus
-- check of what anon actually writes, and that is its own build.
